### ISSUE TITLE
Extension & iptables issues

### ISSUE THREAD

**Issue by 0xPortal** [tenseiken/docker-qbittorrent-wireguard#7] opened 2024-08-30 08:05 UTC
Whenever I try and boot the container, I always get the same error messages regardless of how I create the container:

```
2024-08-30 08:02:31.821636 [INFO] The container is currently running iptables v1.8.10 (nf_tables).
2024-08-30 08:02:31.924330 [INFO] WireGuard config file is found at /config/wireguard/wg0.conf
2024-08-30 08:02:32.024379 [INFO] VPN remote line defined as '146.70.179.34:51820'
2024-08-30 08:02:32.124145 [INFO] VPN_REMOTE defined as '146.70.179.34'
2024-08-30 08:02:32.222312 [INFO] VPN_PORT defined as '51820'
2024-08-30 08:02:32.326010 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.
2024-08-30 08:02:32.420109 [INFO] VPN_DEVICE_TYPE set as 'wg0', since WireGuard will always be wg0.
2024-08-30 08:02:32.515912 [INFO] LAN_NETWORK defined as '192.168.1.0/24'
2024-08-30 08:02:32.611117 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers
2024-08-30 08:02:32.707691 [INFO] Adding 1.1.1.1 to resolv.conf
2024-08-30 08:02:32.806120 [INFO] Adding 8.8.8.8 to resolv.conf
2024-08-30 08:02:32.901460 [INFO] Adding 1.0.0.1 to resolv.conf
2024-08-30 08:02:32.997476 [INFO] Adding 8.8.4.4 to resolv.conf
2024-08-30 08:02:33.095122 [INFO] Starting WireGuard...
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.2.0.2/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
could not detect a useable init system
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
Warning: Extension addrtype revision 0 not supported, missing kernel module?
Warning: Extension comment revision 0 not supported, missing kernel module?
iptables-restore v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
[#] resolvconf -d wg0 -f
could not detect a useable init system
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
```

It seems to complain about a useable init system, complains about no kernel modules for specific features, and iptables not being able to fetch rule set generation id.

Running on a Raspberry Pi 4 with LibreELEC.

**Comment by tenseiken** [comment] 2024-08-30 14:39
I added the ARM option at someone else's request, but I don't have an ARM board to try it out on myself. 

I'm not going to be able to reproduce your situation, but I'd suggest ignoring the "could not detect a useable init system" as some folks are seeing that even though it's still working. I did a quick search for the "Warning: Extension addrtype revision 0 not supported, missing kernel module?" and got a few hits, but it looks like it has to do with the way the kernel is configured. It may be that the distro you're using doesn't have those modules included/enabled.

**Comment by jamie6king** [comment] 2024-09-23 14:07
(0xPortal is now a org, can't access this issue directly)

Yeah I've tried on a different install and it works perfectly. I assume that LibreELEC / Raspberry Pi uses a more basic kernel, so doesn't have those features. Can close this issue.

**Comment by tenseiken** [comment] 2024-09-23 14:10
> Yeah I've tried on a different install and it works perfectly. 

For my own edification, did you get it to work on an Arm distro?

**Comment by jamie6king** [comment] 2024-09-28 16:07
Yup, works perfectly on Raspberry Pi OS, so LibreELEC doesn't have the kernel modules enabled.

**Comment by tenseiken** [comment] 2024-09-28 20:00
Awesome, thanks for confirming. Closing this as resolved.

**Closed by tenseiken** 2024-09-28 20:00 UTC
